### ISSUE TITLE
Android builds (APK)

### ISSUE THREAD

**Issue by tofran** [significa/ios-ipa-app-distribution-server#15]
Although we tried to make the scope of the project very small and restricted, it seems that supporting APK builds is essential.
We have received requests both internal and external. There are already a few forks supporting it.

The requirements are quite simple:

- [ ] Rename the project to app-distribution-server
- [ ] Support uploading and downloading android files

**Comment by EkkoG** [comment]
I have write some code to support this, here is the pr https://github.com/significa/ios-ipa-app-distribution-server/pull/14
